name: base
channels:
  - fastai
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - jupyterlab
  - matplotlib
  - tqdm
  - pandas
  - datasets
  - transformers
  - nbdev
  - spacy
  - inflect
  - anyascii
  - omegaconf
  - hydra-core
  - wandb
  - onnxruntime
  - h5py
  - pre-commit
  - pytest
  - portalocker
  - pip:
    - jupyterlab-quarto
    - torch
    - torchvision
    - torchtext
    - torchaudio
    - plum-dispatch
    - https://github.com/kpu/kenlm/archive/master.zip
    - lhotse
    - phonemizer
    - hydra_colorlog
    - lightning