_target_: nimrod.models.conv.ConvNetX
_partial_: true
num_classes: 10 #default value overridden by hydra at instantiation if necessary

nnet:
  _target_: nimrod.models.conv.ConvNet
  n_features: [1, 8, 16, 32, 16]  # channel/feature expansion
  num_classes: ${..num_classes}  # number of output classes
  kernel_size: 3  # convolution kernel size
  bias: null  # disable bias since using BatchNorm
  normalization: 
    _target_: hydra.utils.get_class
    path: torch.nn.BatchNorm2d
  activation:
    _target_: hydra.utils.get_class
    path: torch.nn.ReLU

# optimizer
# scheduler