defaults:
  _target_: nimrod.models.conv.ConvLayer
  in_channels: 1
  out_channels: 16
  kernel_size: 3
  bias: true
  normalization:
    _target_: hydra.utils.get_class
    path: torch.nn.BatchNorm2d
  activation:
    _target_: hydra.utils.get_class
    path: torch.nn.ReLU

mnist:
  _target_: nimrod.models.conv.ConvLayer
  in_channels: 1
  out_channels: 16
  kernel_size: 3
  bias: false
  normalization:
    _target_: hydra.utils.get_class
    path: torch.nn.BatchNorm2d
  activation:
    _target_: hydra.utils.get_class
    path: torch.nn.ReLU
