defaults:
  _target_: nimrod.models.conv.ConvNet
  n_features: [1, 8, 16, 32, 64]  # channel/feature expansion
  num_classes: 10  # number of output classes
  kernel_size: 3  # convolution kernel size
  bias: false  # disable bias since using BatchNorm
  normalization: 
    _target_: hydra.utils.get_class
    path: torch.nn.BatchNorm2d
  activation:
    _target_: hydra.utils.get_class
    path: torch.nn.ReLU
