_target_: nimrod.models.diffusion.DiffusorX
_partial_: true # we init optim & sched later

nnet:
  _target_: diffusers.UNet2DModel
  block_out_channels: [32, 64, 128, 256]
  sample_size: 32
  in_channels: 1
  out_channels: 1

noise_scheduler:
  _target_: diffusers.DDPMScheduler
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012


# optimizer
# scheduler%                 