defaults:
  - _self_

model:
  - _target_: nimrod.models.conv.ConvLayer
    in_channels: 1
    out_channels: 16
    kernel_size: 3
    bias: true
    normalization:
      _target_: hydra.utils.get_class
      path: torch.nn.BatchNorm2d
    activation:
      _target_: hydra.utils.get_class
      path: torch.nn.ReLU

  - _target_: nimrod.models.conv.ConvLayer
    in_channels: 16
    out_channels: 32
    kernel_size: 3
    bias: true
    normalization:
      _target_: hydra.utils.get_class
      path: torch.nn.BatchNorm2d
    activation:
      _target_: hydra.utils.get_class
      path: torch.nn.ReLU