model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true
  verbose: true
  dirpath: checkpoints/
  filename: epoch_{epoch:03d}
  auto_insert_metric_name: true
early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss
  mode: min
  patience: 10
  min_delta: 0
