model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true
  verbose: true
  dirpath: ${ckpt_dir}
  filename: epoch_{epoch:03d}
  auto_insert_metric_name: true