model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true
  verbose: true
  dirpath: ${paths.output_dir}/checkpoints
  filename: {epoch:03d}-{val_loss:.2f}
  auto_insert_metric_name: true