model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/loss"
  mode: min
  save_top_k: 1
  save_last: True
  verbose: True
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch{epoch:03d}-val_loss{val/loss:.2f}"
  auto_insert_metric_name: False