train:
  _target_: nimrod.data.datasets.MNISTDataset
  data_dir: "~/Data"
  train: True
  transform:
    _target_: torchvision.transforms.ToTensor
test:
  _target_: nimrod.data.datasets.MNISTDataset
  data_dir: "~/Data"
  train: False
  transform:
    _target_: torchvision.transforms.ToTensor