# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/image.clip.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/image.clip.ipynb 4
from PIL import Image
import requests
from pathlib import Path
from transformers import CLIPProcessor, CLIPModel
from datasets import load_dataset
import torch
from tqdm import tqdm
import numpy as np
