# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/audio.embeddings.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/audio.embeddings.ipynb 4
from encodec import EncodecModel
from encodec.utils import convert_audio
import torchaudio
import torch
from matplotlib import pyplot as plt
from .utils import plot_waveform
import IPython.display as ipd
