# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nimrod',
                'doc_host': 'https://slegroux.github.io',
                'git_url': 'https://github.com/slegroux/nimrod',
                'lib_path': 'nimrod'},
  'syms': { 'nimrod.core': { 'nimrod.core.foo': ('core.html#foo', 'nimrod/core.py'),
                             'nimrod.core.test': ('core.html#test', 'nimrod/core.py')},
            'nimrod.data.datasets': { 'nimrod.data.datasets.ImageDataset': ('data.datasets.html#imagedataset', 'nimrod/data/datasets.py'),
                                      'nimrod.data.datasets.ImageDataset.show': ( 'data.datasets.html#imagedataset.show',
                                                                                  'nimrod/data/datasets.py'),
                                      'nimrod.data.datasets.MNISTDataset': ('data.datasets.html#mnistdataset', 'nimrod/data/datasets.py'),
                                      'nimrod.data.datasets.MNISTDataset.__getitem__': ( 'data.datasets.html#mnistdataset.__getitem__',
                                                                                         'nimrod/data/datasets.py'),
                                      'nimrod.data.datasets.MNISTDataset.__init__': ( 'data.datasets.html#mnistdataset.__init__',
                                                                                      'nimrod/data/datasets.py'),
                                      'nimrod.data.datasets.MNISTDataset.__len__': ( 'data.datasets.html#mnistdataset.__len__',
                                                                                     'nimrod/data/datasets.py')}}}
