# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nimrod',
                'doc_host': 'https://slegroux.github.io',
                'git_url': 'https://github.com/slegroux/nimrod',
                'lib_path': 'nimrod'},
  'syms': {'nimrod.core': {'nimrod.core.foo': ('core.html#foo', 'nimrod/core.py')}}}
