# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_models.ipynb.

# %% auto 0
__all__ = ['foo', 'test']

# %% ../nbs/02_models.ipynb 3
from . import modules

# %% ../nbs/02_models.ipynb 4
def foo(): pass

# %% ../nbs/02_models.ipynb 5
def test():
    pass
