"""Utilities to avoid re-inventing the wheel"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['FORMAT', 'logger', 'get_device', 'set_seed']

# %% ../nbs/utils.ipynb 4
import torch
import lightning as L

import logging
from rich.logging import RichHandler



# %% ../nbs/utils.ipynb 5
FORMAT = "[%(asctime)s] %(levelname)s - %(message)s"
logging.basicConfig(
    level=logging.INFO, format=FORMAT, datefmt='%H:%M:%S',
    # handlers=[RichHandler(rich_tracebacks=True)]#, tracebacks_suppress=[matplotlib, L])]
)
logger = logging.getLogger(__name__)

# %% ../nbs/utils.ipynb 6
def get_device():
    device = 'mps' if torch.backends.mps.is_available() else 'cuda' if torch.cuda.is_available() else 'cpu'
    logger.info(f"Using device: {device}")
    return device

# %% ../nbs/utils.ipynb 10
def set_seed(seed: int = 42) -> None:
    # np.random.seed(seed)
    # random.seed(seed)
    # torch.manual_seed(seed)
    # torch.cuda.manual_seed(seed)
    # # When running on the CuDNN backend, two further options must be set
    # torch.backends.cudnn.deterministic = True
    # torch.backends.cudnn.benchmark = False
    # # Set a fixed value for the hash seed
    # os.environ["PYTHONHASHSEED"] = str(seed)
    # print(f"Random seed set as {seed}")
    L.seed_everything(seed, workers=True)
