wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${project}
  name: ${name}
  save_dir: "${paths.output_dir}"
  offline: False # store only locally
  id: null # give id to resume experiment
  entity: "slegroux"
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: ["tag0"]