# @package _global_

defaults:
  - _self_
  - callbacks: default
  - logger: wandb
  - datasets: mnist
  - dataloaders: default
  - trainer: default
  - paths: default
  - hydra: default

project: "autoencoder"
ckpt_path: null # ckpt to resume training from
seed: 42
test: True
train: True
ignore_warnings: True
tags: ["dev"]