version:  '3'
services:
  jupyterlab:
      image: nimrod-test
      volumes:
        - /Users/syl20/Data:/home/data
      ports:
        - 8888:8888
      container_name: nimrod_jupyter
      env_file:
        - env-file
      command:
        - ./command.sh
        # - "jupyter lab --allow-root --ip=0.0.0.0 --no-browser --ServerApp.trust_xheaders=True --ServerApp.disable_check_xsrf=False --ServerApp.allow_remote_access=True --ServerApp.allow_origin='*' --ServerApp.allow_credentials=True"
        # - git clone https://github.com/slegroux/nimrod
        # - "jupyter lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''"
      # command: "./start_jupyterlab.sh"
      # command: "start-notebook.sh \
      #   --NotebookApp.password=${ACCESS_TOKEN} \
      #   --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem"