version:  '3'
services:
  jupyterlab:
    image: nimrod-test
    volumes:
      - /Users/syl20/Data:/home/data
    ports:
      - 8888:8888
    container_name: nimrod_jupyter
    env_file:
      - env-file
    command: ./command.sh