version:  '3'
services:
  jupyterlab:
      image: slegroux/nimrod
      volumes:
        - /Users/syl20/Data:/home/data
      ports:
        - 8888:8888
      container_name: nimrod_jupyter
      command: "jupyter lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''"
      # command: "./start_jupyterlab.sh"
      # command: "start-notebook.sh \
      #   --NotebookApp.password=${ACCESS_TOKEN} \
      #   --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem"