datamodule:
  _target_: nimrod.text.datasets.CharDataModule
  data_path: "../../data/text/tiny_shakespeare.txt"
  train_val_test_split: [0.8, 0.1, 0.1]
  batch_size: 1024
  context_size: 3
  num_workers: 0
  pin_memory: False
  persistent_workers: False

model:
  _target_: nimrod.models.lm.NNLM_L
  n_vocab: 70
  n_emb: 10
  n_context: 3
  n_h: 100  
