project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Nimrod"
  description: "A minimal deep learning framework"
  repo-url: "https://github.com/slegroux/nimrod"
  repo-branch: main
  site-url: "https://slegroux.github.io/nimrod"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: docked


metadata-files: [nbdev.yml, sidebar.yml]