# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/text.embeddings.ipynb.

# %% auto 0
__all__ = ['Encoder', 'Decoder']

# %% ../../nbs/text.embeddings.ipynb 4
import torch.nn as nn
import torch

# %% ../../nbs/text.embeddings.ipynb 5
class Encoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Sequential(nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 3))

    def forward(self, x):
        return self.l1(x)


class Decoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Sequential(nn.Linear(3, 64), nn.ReLU(), nn.Linear(64, 28 * 28))

    def forward(self, x):
        return self.l1(x)
