"""Neural net modules"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.diffusion.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../../nbs/models.diffusion.ipynb 3
import torch.nn as nn
import torch.nn.functional as F
import torch
from torchvision.transforms import transforms

import os
import logging
import warnings
from omegaconf import OmegaConf
from hydra.utils import instantiate
from tqdm.notebook import tqdm
from dataclasses import dataclass

from matplotlib import pyplot as plt
import numpy as np

from ..utils import get_device, set_seed, time_it
from ..image.datasets import ImageDataset, show_images, make_grid

from diffusers import UNet2DModel, DDPMScheduler, DDPMPipeline
from diffusers.utils import make_image_grid
from diffusers.optimization import get_cosine_schedule_with_warmup

# %% ../../nbs/models.diffusion.ipynb 4
set_seed(42)
logger = logging.getLogger(__name__)
warnings.filterwarnings("ignore", category=UserWarning, module="matplotlib.image")
