# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.mlp.ipynb.

# %% auto 0
__all__ = ['MLP']

# %% ../../nbs/models.mlp.ipynb 3
import torch.nn as nn
import torch

# %% ../../nbs/models.mlp.ipynb 4
class MLP(nn.Module):
    def __init__(self, n_in=32*32*3, n_h=64, n_out=10):
        super().__init__()
        l1 = nn.Linear(n_in, n_h)
        l2 = nn.Linear(n_h, n_out)
        relu = nn.ReLU()
        self.layers = nn.Sequential(l1,l2,relu)
        
    def forward(self, x):
        return self.layers(x)

