# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.transformer.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/models.transformer.ipynb 4
import torch.nn as nn
import torch
import torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence
from torch.optim import SGD
from torchtext.vocab import vocab

from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm

from typing import Dict, List, Tuple, Optional, Set
from collections import Counter, OrderedDict
from dataclasses import dataclass, asdict

from plum import dispatch

from .lm import Vocab
