# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.transformer.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/models.transformer.ipynb 4
# torch
import torch.nn as nn
import torch
import torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence
from torch.optim import SGD
from torchtext.vocab import vocab

# hf
import datasets

# data 
import pandas as pd
import numpy as np

# ui
from matplotlib import pyplot as plt
from tqdm.notebook import tqdm

# python
from typing import Dict, List, Tuple, Optional, Set
from collections import Counter, OrderedDict
from dataclasses import dataclass, asdict
from plum import dispatch

# nimrod
from .lm import Vocab
