"""Neural net model"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.unet.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../../nbs/models.unet.ipynb 4
import torch.nn as nn
import torch.nn.functional as F
import torch
from torch_lr_finder import LRFinder

from omegaconf import OmegaConf
from hydra.utils import instantiate

from matplotlib import pyplot as plt

from .conv import ConvLayer
from .resnet import ResBlock
from ..utils import get_device, set_seed

from typing import List
import logging

# %% ../../nbs/models.unet.ipynb 5
logger = logging.getLogger(__name__)
set_seed()
