"""Using Hugging Face Diffusion Pipeline"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/tutorials.stablediffusion.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/tutorials.stablediffusion.ipynb 4
import torch
from torch import autocast
from torchvision import transforms as tfms
from diffusers import AutoencoderKL, LMSDiscreteScheduler, UNet2DConditionModel
from huggingface_hub import notebook_login
from transformers import CLIPTextModel, CLIPTokenizer
import transformers

from IPython.display import HTML
from matplotlib import pyplot as plt
from pathlib import Path
from PIL import Image
from tqdm.auto import tqdm

from base64 import b64encode
import os
from ..utils import get_device, set_seed

import logging

