wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.33.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1697596536.827018
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      3:
      - 23
      4: 3.11.5
      5: 0.15.12
      6: 4.33.3
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
