_target_: nimrod.models.conv.ConvNetX
num_classes: 10

nnet:
  _target_: nimrod.models.conv.ConvNet
  in_channels: 1
  out_channels: ${num_classes}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 1e-5 # mild regularization

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10