# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../nbs/text.models.transformer.classification.ipynb.

# %% auto 0
__all__ = []

# %% ../../../../nbs/text.models.transformer.classification.ipynb 2
# torch
import torch.nn as nn
import torch
import torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence
from torch.optim import SGD
from torchtext.vocab import vocab
from torch.nn import TransformerEncoder, TransformerEncoderLayer

# hf
import datasets
from datasets import list_datasets, load_dataset
from transformers import AutoTokenizer, AutoModel

# data 
import pandas as pd
import numpy as np

# ui
from matplotlib import pyplot as plt
from tqdm.notebook import tqdm

# python
from typing import Dict, List, Tuple, Optional, Set
from collections import Counter, OrderedDict
from dataclasses import dataclass, asdict
from plum import dispatch
import math
