name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: sudo apt-get install espeak
        shell: bash
      - run: pip install spacy && python -m spacy download en_core_web_sm
        shell: bash
      - uses: fastai/workflows/nbdev-ci@master