name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: apt-get install espeak
        shell: bash
      - uses: fastai/workflows/nbdev-ci@master