name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get  install espeak
          python -m pip install --upgrade pip
          pip install nbdev torch torchvision requests
          pip install -e ".[dev]"

      - name: Diagnostic Information
        run: |
          python -c "import torch; print('Torch version:', torch.__version__)"
          python -c "import torchvision; print('Torchvision version:', torchvision.__version__)"
          python -c "import os; print('Current working directory:', os.getcwd())"
          python -c "import sys; print('Python path:', sys.path)"

      - name: Clean notebooks
        run: |
          nbdev_clean

      - name: Export notebooks
        run: |
          nbdev_export

      - name: Run tests
        run: |
          nbdev_test --do_print --timing