name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: sudo apt-get install espeak git-lfs
        shell: bash
      - run: git lfs install
      - run: git lfs fetch --all && git lfs checkout
      # - uses: fastai/workflows/nbdev-ci@master